[package]
name = "day12_n_body_problem"
version = "0.1.0"
authors = ["Dima Lazarev <dmitry.lazarev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
